version: "3.7"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: videoviz
      MYSQL_ROOT_PASSWORD: videoviz
      MYSQL_USER: videoviz
      MYSQL_PASSWORD: videoviz
    restart: always
    ports:
    - "3306:3306"

