version: "3.7"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: videoviz
      MYSQL_ROOT_PASSWORD: videoviz
      MYSQL_USER: videoviz
      MYSQL_PASSWORD: videoviz
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/kvnsu/docker-shared/mysql:/var/lib/mysql
  java:
    build:
      context: ../
      dockerfile: ./docker/java/Dockerfile
    container_name: java-container
    restart: always
    environment:
      - spring_profiles_active=docker
    ports:
      - "8080:8080"
    volumes:
    - C:/Users/kvnsu/IdeaProjects/videoviz/videoviz-gui/gui:/var/www/html/gui
    - C:/Users/kvnsu/mydata:/mydata
    depends_on:
      - database